Fix compiler errors due to const incorrectness
Passing a const string into strrchr() and friends may cause the compiler
to make the return value a const char* (via _Generic) which causes the
following -Werror:

../panels/applications/cc-applications-panel.c: In function ‘add_scheme’:
../panels/applications/cc-applications-panel.c:1119:10: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
 1119 |   scheme = strrchr (type, '/') + 1;

../panels/network/cc-wifi-connection-row.c: In function ‘update_ui’:
../panels/network/cc-wifi-connection-row.c:207:16: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  207 |       ssid_pos = strstr (name, ssid_str);
      |                ^

../panels/network/connection-editor/ce-page.c: In function ‘ce_page_trim_address’:
../panels/network/connection-editor/ce-page.c:224:15: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  224 |         space = strchr (addr, ' ');
      |               ^